### ISSUE TITLE
issue with queue.js and embeds.js in the embed messages. "Requested by" section

### ISSUE THREAD

**Issue by RJ1002** [wtfnotavailable/Discord-MusicBot#146]
## Please describe the problem you are having in as much detail as possible:
I noticed that some of the embeds have an issue where there extra text that is not needed in the "Requested by" section of the embed.
They are in queue.js and embeds.js
I was going to make a Poll request but I was not sure if it was just a Windows issue or not.

## Include a reproducible code sample here, if possible, the snippet of code which is throwing the error or which you presume is giving issues:
**queue.js:**
Between 78-84:
```js
				.setFields([
					{
						name: "Requested by",
						value: `<@${song.requester}>`,
						inline: true,
					},
				])
```
The fix that I did:
```js
				.setFields([
					{
						name: "Requested by",
						value: `${song.requester}`,
						inline: true,
					},
				])
```
Between 115-121:
```js
			.setFields([
				{
					name: "Requested by",
					value: `<@${song.requester}>`,
					inline: true,
				},
			])
```
The fix I did:
```js
			.setFields([
				{
					name: "Requested by",
					value: `${song.requester}`,
					inline: true,
				},
			])
```
**embeds.js:**
Between 78-84:
```js
      .addFields([
        {
          name: "Requested by",
          value: `<@${track.requester}>`,
          inline: true,
        },
        {
```
The fix I did:
```js
      .addFields([
        {
          name: "Requested by",
          value: `${track.requester}`,
          inline: true,
        },
        {
```
## If you have your own setup, without the original docker configuration, please provide:
running it in Windows 10 in node.js.

## Further details:

- discord.js version: 14.13.0
- Node.js version: 18.15.0
- Operating system: windows 10
- Priority this issue should have – please be realistic and elaborate if possible: LOW (not a big deal just a cosmetic issue)

## Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by BioCla** [comment]
Yes, for whatever reason there's some issues with that where sometimes it shows correctly and sometimes it does not. If you want to make a PR for this in the meantime I'll gladly review it and merge

**Comment by RJ1002** [comment]
> If you want to make a PR for this in the meantime I'll gladly review it and merge

okay I will
