### ISSUE TITLE
irrelevant stats information

### ISSUE THREAD

**Issue by BioCla** [wtfnotavailable/Discord-MusicBot#173]
In case the bot were to be connected to more than one lavalink the relevant stats shown with the `/stats` command would only show the first node (which is a bit misleading)
https://github.com/wtfnotavailable/Discord-MusicBot/blob/d25d06741a08cb2028432a49640ee43e01e5386f/djs-bot/commands/utility/stats.js#L61-L71
The lines above should be removed or changed to show an aggregate info of all the nodes that are connected

**Comment by LewdHuTao** [comment]
this was fixed in the latest commit
