### ISSUE TITLE
Add support to previous, play/pause and next keyboard shortcuts when using the web player

### ISSUE THREAD

**Issue by NereaCassian** [wtfnotavailable/Discord-MusicBot#176]
It would be useful to be able to control the web player using the previous, play/pause and next keyboard shortcuts like you do in the web version of Spotify for example. This way you can control the bot without commands or while doing other thing. 

Btw, the dashboard is looking neat, you are doing an awesome job.

**Comment by Neko-Life** [comment]
how does this work @NereaCassian ?
smt like
```md
Space: play/pause
Right arrow: next
Left arrow: previous
```
like that?

**Comment by NereaCassian** [comment]
Most of keyboards have a keys with a secondary actions that lets you go back to the previous song, skip to the next o play pause the reproduction.

![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/70113068/675041b7-5ebb-4ca6-ba3c-c99a33727422)


Most of the websites that reproduces media support that you press this keys to control the reproduction. I don't know exactly how to add support to it in next js but I will try tu investigate it and do a PR now that I'm learning a little about nextjs and react.

**Comment by Neko-Life** [comment]
> Most of keyboards have a keys with a secondary actions that lets you go back to the previous song, skip to the next o play pause the reproduction.
> 
> ![image](https://private-user-images.githubusercontent.com/70113068/289348822-675041b7-5ebb-4ca6-ba3c-c99a33727422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDExMDAsIm5iZiI6MTcwMjIwMDgwMCwicGF0aCI6Ii83MDExMzA2OC8yODkzNDg4MjItNjc1MDQxYjctNWViYi00Y2E2LWJhM2MtYzk5YTMzNzI3NDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA5MzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZmM5YzViMDA1OGVkZDgyZDMzN2VjMDk1NTkyNzk5ZGEyNzUwODc4ODljNGFkNDNkMDY0MGJiODYyMWJiOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ynW4vpzZfpBnls26ffGESZesbxI5G0Nz3wBNR6uH0g4)
> 
> Most of the websites that reproduces media support that you press this keys to control the reproduction. I don't know exactly how to add support to it in next js but I will try tu investigate it and do a PR now that I'm learning a little about nextjs and react.

hmm my keyboard doesn't have those keys so idk :sob:

See #181 the base functionality is complete, u only need to register more shortcut with key combination and a callback handler (what the shortcut have to do when pressed) in case u want to experiment. See how the code for `Ctrl+/` that currently only shows a broken modal https://github.com/wtfnotavailable/Discord-MusicBot/pull/181/files#diff-93585f108808bb270bc6cb282fdeb01b5cfaef658bcc22a74522290468099b47R91-R94

**Comment by Neko-Life** [comment]
@NereaCassian if u still want to add those media keys, find out what key it has by logging keyboard event and just add entries like [this](https://github.com/wtfnotavailable/Discord-MusicBot/pull/181/files#diff-60930c5633116e85ac5f5032e03e3ff4215ff9096dba12c4054e67a4756639aeR444-R458) and do the same [register unregister](https://github.com/wtfnotavailable/Discord-MusicBot/pull/181/files#diff-60930c5633116e85ac5f5032e03e3ff4215ff9096dba12c4054e67a4756639aeR460-R470), u can see the current shortcut with `Ctrl+/` in the server player page. thank u.

**Comment by Neko-Life** [comment]
hmm i should have integrated it with the modal shortcut directly instead of hardcoding it, that's for next weekend ig
