### ISSUE TITLE
[Lite version] "No database configured" error when trying to play song.

### ISSUE THREAD

**Issue by mitch1887** [wtfnotavailable/Discord-MusicBot#183]
## Please describe the problem you are having in as much detail as possible:
When I run the lite version with "make lite" I get a "Error: No database configured" message despite me not running it with the 'db' option.
## Include a reproducible code sample here, if possible, the snippet of code which is throwing the error or which you presume is giving issues:

```js
[13:11:2023 - 23:12] [ERROR] | [FATAL] Possibly Uncaught Exception
        Reason: Error: No database configured

uncaughtException

```
## If you have your own setup, without the original docker configuration, please provide:

I have both DATABASE and DATABASE_URL set to "" in the .env file
Running the latest master branch with Node.js v21.4.0 on Arch Linux.

**Comment by rakosi2** [comment]
Yes, it appears that a DB is currently required even though the config says that you can db-less
https://github.com/wtfnotavailable/Discord-MusicBot/blob/develop/djs-bot/util/controlChannel.js#L26
