### ISSUE TITLE
Error: Cannot find module '../api/v1/dist

### ISSUE THREAD

**Issue by XstreamSpeed** [wtfnotavailable/Discord-MusicBot#187]
## Please describe the problem you are having in as much detail as possible:
In djs-bot/lib/Bot.js, there seems to be a problem, **app** and **wsApp** are being called from api/v1/**dist**, except that the dist folder isn't actually there I've checked this git branch and it doesn't seem to be a problem that is on my end because the folder is not on git either.

## Include a reproducible code sample here, if possible, the snippet of code which is throwing the error or which you presume is giving issues:
![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/79592017/598e2720-67db-4eb7-bee5-afb34621c35d)

```js
const { app, wsApp } = require("../api/v1/dist");
```
## Further details:

- discord.js version: 14.8.0
- Node.js version: v18.19.0
- Operating system: don't know, using ptero
- Priority this issue should have – please be realistic and elaborate if possible:

## Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by ntrzr** [comment]
Same issue here.

**Comment by Neko-Life** [comment]
Read the [readme](https://github.com/wtfnotavailable/Discord-MusicBot#written-setup) and you will find a link to the [installation procedure for the bot](https://github.com/wtfnotavailable/Discord-MusicBot/blob/master/djs-bot/README.md)
