### ISSUE TITLE
Cannot seem to start Develop Branch

### ISSUE THREAD

**Issue by Slacker101** [wtfnotavailable/Discord-MusicBot#191]
## Please describe the problem you are having in as much detail as possible:
Simply using make up on the development branch, should I be using master instead?
First issue is that oddly it's skipping djs-bot. Then the table parsing issue, which I'm not sure which table it is trying to parse.
```
user@SERVER:~/Docker/Discord-MusicBot-v5-1/Discord-MusicBot$ sudo make up
    OS: Linux
    ARCHITECURE: x86_64
    PROJECT_NAME: discord-musicbot
    PROJECT_PATH: /home/nate/Docker/Discord-MusicBot-v5-1/Discord-MusicBot

format value "table" could not be parsed: parsing failed
format value "table" could not be parsed: parsing failed
Pulling images for: djs-bot dashboard postgres-db lavalink
WARN[0000] The "JWT_SECRET_KEY" variable is not set. Defaulting to a blank string. 
[+] Running 4/4
 ⠿ djs-bot Skipped                                                         0.0s
 ⠿ lavalink Pulled                                                         4.4s
 ⠿ dashboard Pulled                                                        5.0s
 ⠿ postgres-db Pulled                                                      4.8s

Creating container for: djs-bot dashboard postgres-db lavalink
unknown flag: --pull

Starting djs-bot dashboard postgres-db lavalink
no container found for project "discord-musicbot": not found
```
## Include a reproducible code sample here, if possible, the snippet of code which is throwing the error or which you presume is giving issues:

Env has the following defined
```js
POSTGRES=root
POSTGRES_USER=root
POSTGRES_PASSWORD=root
TOKEN={redacted}
CLIENTID={redacted}
CLIENTSECRET={redacted}
DEVUID={redacted}
DATABASE_URL="postgres://root:root@localhost:5432/base"
```
## If you have your own setup, without the original docker configuration, please provide:
I do not, I copied my .env from the old repo for this to this new one.
## Further details:
Full development branch, whatever is in there unmodified other than my .env
- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

## Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by Slacker101** [comment]
After posting this I thought maybe make wasn't happy with an old version of the image existing and thus skipping, removed it from docker but that was not it.

Also realized after looking at the default .env template you have it's now in the /djs-bot/ and has the JWT and a couple other fields as well as a changed postgres address, which I assume was updated in the docker compse but didn't check. Including the new information and switching address also did not fix it. Thought I did not think the latter would given we seem to be stuck way earlier than establishing the db connection.

**Comment by BioCla** [comment]
make sure you have the latest docker version installed with the compose plugin, the real error is only `unknown flag: --pull`

**Comment by Slacker101** [comment]
> make sure you have the latest docker version installed with the compose plugin, the real error is only `unknown flag: --pull`

Unfortunately that does not seem to be the issue
![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/14153962/8983285d-9d1c-4bd9-8cea-caac4dad6968)

**Comment by BioCla** [comment]
please make sure you are using docker with the compose **plugin**, not the standalone `docker-compose` executable, and that it is on the latest version.
use `docker compose version` to verify this.

You can verify this in the `dc.sh` script where:
https://github.com/wtfnotavailable/Discord-MusicBot/blob/66ab8c5fe655a25c97b700dc8d88434454e4f93b/dc.sh#L43-L45
Shows how the docker command is structured and then:
https://github.com/wtfnotavailable/Discord-MusicBot/blob/66ab8c5fe655a25c97b700dc8d88434454e4f93b/dc.sh#L114-L115
how it's used in the context of your error.

The only reason I can think of as to why you are getting that error is that you do indeed have a `docker compose` installation, but it may not be up to date or it may just be aliasing the standalone executable, which does not have the full set of options of the plugin

**Comment by Slacker101** [comment]
Hmm, I validated that I have docker compose plugin,  v2.6.1 and I see the command when I run docker compose build --help.

I am still getting the same error.
