### ISSUE TITLE
Support for a lavalink-client which has lavalink v4 support

### ISSUE THREAD

**Issue by ryu0q** [wtfnotavailable/Discord-MusicBot#201]
## Is your feature request related to a problem? Please describe.

Problem: The currently-being-used erela.js lacks support for lavalink v4.

## Describe the ideal solution

Migrate the project to a newer player: https://github.com/tomato6966/lavalink-client

## Describe alternatives you've considered

The updated erela.js from the same author: https://github.com/tomato6966/

**Comment by DarrenOfficial** [comment]
Soon,
![](https://lore.dpaste.org/g/LCoMPBNr39.png)

**Comment by DarrenOfficial** [comment]
^ Screenshot from January 3rd 2024

**Comment by Neko-Life** [comment]
Soon™️

**Comment by DarrenOfficial** [comment]
😉 very Soon:tm:

**Comment by kaiyga** [comment]
What a latest Lavalink version in use? 3.7.10 Not work

**Comment by DarrenOfficial** [comment]
> What a latest Lavalink version in use? 3.7.10 Not work


https://repo.lavalink.dev/artifacts/lavalink/219dfdd0/Lavalink.jar

**Comment by AdamT20054** [comment]
Is lavalink V4 supported as of now?

**Comment by LewdHuTao** [comment]
> Is lavalink V4 supported as of now?

Soon™

**Comment by Checker8763** [comment]
> What a latest Lavalink version in use? 3.7.10 Not work

1. Most uptodate Lavalinkv3: 3.7.12
2. configure youtube-source plugin for lavalink v3 from the official lavalink devs
3. Use the bot as normal with lavalink v3

https://github.com/lavalink-devs/youtube-source
