### ISSUE TITLE
Issue with fastify v4.26.0

### ISSUE THREAD

**Issue by RJ1002** [wtfnotavailable/Discord-MusicBot#204]
## Please describe the problem you are having in as much detail as possible:
so I grabbed the latest version(5.5.0) and ran the `npm run update` and it ran fine. but every time you try to start it gives the following error after `> tsc -p api/v1/tsconfig.json`: 

![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/22334486/e33a4c71-9c83-47cc-a59e-b17c07b368fe)
![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/22334486/118db0d4-649b-47c8-b6c9-c1c395579949)

I'm able to fix it by setting fastify to 4.25.0 in package.json:
![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/22334486/e74574a4-dc89-45d9-a5ce-ec3004d09377)

## Include a reproducible code sample here, if possible, the snippet of code which is throwing the error or which you presume is giving issues:
so maybe a change to fastify broke something or it an issue with my nodejs/windows 10.
it seems to be related to deploying the slash commands since it also throws an error when running `npm run deploy`
it seems to start in djs-bot/api/v1/src/index.ts

## Further details:

- discord.js version: 14.14.1
- Node.js version: 18.15.0
- Operating system: windows 10
- Priority this issue should have – please be realistic and elaborate if possible: low since the bot will still work if I set fastify to 4.25.0.

## Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by Neko-Life** [comment]
should be fixed in v5.5.1 now
