### ISSUE TITLE
WS and API port interverted in config.js default

### ISSUE THREAD

**Issue by Epoustouflant** [wtfnotavailable/Discord-MusicBot#210]
In the config.js file, the default port for api and ws (line 46 and 56) are interverted. The ws' port is 8080 instead of 3000 and the other way around.

![Capture d'écran 2024-02-20 190305](https://github.com/wtfnotavailable/Discord-MusicBot/assets/54931269/ed013c8e-121d-4d31-b4e6-346e7cce2d5d)

**Comment by DarrenOfficial** [comment]
Is this intentional @BioCla?

**Comment by brianferri** [comment]
if it doesn't work out of the box, it's not intentional :P
you can make a PR fixing it 🙏

**Comment by DarrenOfficial** [comment]
Thank you for the update, I will make a PR fixing this soon

**Comment by DarrenOfficial** [comment]
Resolved https://git.dpaste.org/dmb/Discord-MusicBot/pulls/214
