### ISSUE TITLE
Error: Used disallowed intents

### ISSUE THREAD

**Issue by Vic378** [wtfnotavailable/Discord-MusicBot#226]
Hi, I've been trying to make the jump from the beta 5.0.0 bot to the current version but I have not been successful in bringing it to life. Whenever i try to run "make up no-docker" or manually "npm run start" and "npm run start" I get this error.
![boterror](https://github.com/wtfnotavailable/Discord-MusicBot/assets/71328720/1d301b53-5467-4abd-a034-a8c8dcc945c8)
Did I mess up the configuration or the perms when inviting the bot?

**Comment by LewdHuTao** [comment]
Enable all intents on discord dev portal

**Comment by Vic378** [comment]
Nvm I found the issue I didnt activate these new toggles on the developer portal
![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/71328720/7e9f812e-e738-4605-88a9-625b8a66af5e)

**Comment by Vic378** [comment]
> Enable all intents on discord dev portal

Yes I just found it hahahah thank you ^^
