### ISSUE TITLE
/search shows wrong song data in "added to queue" message

### ISSUE THREAD

**Issue by PandaDriver156** [wtfnotavailable/Discord-MusicBot#232]
## Please describe the problem you are having in as much detail as possible:
Selecting a song from search results will add the correct song to queue, but displays data of the 1st song in search result in the "added to queue" embed message.
![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/46034537/c324657d-cb86-440d-9cf5-ad8d0bb68ea2)

Looking at the code, it's probably because in `search.js` in the embed `res.tracks[0]` is used instead of `trackForPlay.tracks[0]`.

At this point I could have made a PR, let me know if i should do that.
## Include a reproducible code sample here, if possible, the snippet of code which is throwing the error or which you presume is giving issues:
in `search.js`:
```js
i.editReply({
            content: null,
            embeds: [
              new EmbedBuilder()
                .setAuthor({
                  name: "Added to queue",
                  iconURL: client.config.iconURL,
                })
                .setURL(res.tracks[0].uri)
                .setThumbnail(res.tracks[0].displayThumbnail("maxresdefault"))
                .setDescription(
                  `[${trackForPlay?.tracks[0]?.title}](${trackForPlay?.tracks[0].uri})` ||
                    "No Title"
                )
                .addFields(
                  {
                    name: "Added by",
                    value: `<@${interaction.user.id}>`,
                    inline: true,
                  },
                  {
                    name: "Duration",
                    value: res.tracks[0].isStream
                      ? `\`LIVE :red_circle:\``
                      : `\`${client.ms(res.tracks[0].duration, {
                          colonNotation: true,
                        })}\``,
                    inline: true,
                  }
                )
                .setColor(client.config.embedColor),
            ],
            components: [],
          });
```
## If you have your own setup, without the original docker configuration, please provide:
Unrelated
## Further details:

- discord.js version: 14.15.2
- Node.js version: 20.14.0
- Docker version: 26.1.3
- Operating system: Ubuntu 22.04
- Priority this issue should have – please be realistic and elaborate if possible: a bit annoying, but not terrible. Though the fix seems easy (i hope)

## Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by Neko-Life** [comment]
PRs r welcome

**Comment by Vic378** [comment]
I have the same problem, is there any solution?

**Comment by LewdHuTao** [comment]
fixed :D
