### ISSUE TITLE
[DJS-BOT] - Player control buttons

### ISSUE THREAD

**Issue by C-EO** [wtfnotavailable/Discord-MusicBot#39]
## Is your feature request related to a problem? Please describe.

> @BioCla One of the reasons I liked v5 is because it had buttons. It would be pointless to create a v5.1 without buttons
> 
> The player needs the buttons for they simplified the work in addition to the pause, play, stop, and volume commands
> 
> _Originally posted by @C-EO in https://github.com/SudhanPlayz/Discord-MusicBot/issues/1227#issuecomment-1599473535_
            

## Describe the ideal solution

> I'll take that as a suggestion. I was already planning on reimplementing them under a different dress:
> Instead of having it be on the player message itself it would be in a dedicated channel (kinda like hydra).
> 
> I'll try to reimplement it as you suggested as well
> 
> _Originally posted by @BioCla in https://github.com/SudhanPlayz/Discord-MusicBot/issues/1227#issuecomment-1599509202_

## Describe alternatives you've considered

None

## Additional context

Can't access them

**Comment by Neko-Life** [comment]
@BioCla how will it work? should admin mark a channel as control channel with some command and then send a sticky message with buttons in there?

**Comment by BioCla** [comment]
> @BioCla how will it work? should admin mark a channel as control channel with some command and then send a sticky message with buttons in there?

They would be two separate features:

 - Dedicated query channel should be selected by a DJ/admin (the dedicated command takes a channel as a parameter): spawns and pins a few messages with instructions and control buttons, sets a cool down on the channel. Every message sent in there will be a query to the Lavalink and results will be added to the queue (standard play command functions)
 - `Now playing message` should have 5 buttons (vol. Up/Down, Next/Prev. Song, toggle play)

**Comment by C-EO** [comment]
@BioCla would it need giving the bot a DJ Role too?

**Comment by BioCla** [comment]
> @BioCla would it need giving the bot a DJ Role too?

Not necessarily
