### ISSUE TITLE
Ability to use Spotify 

### ISSUE THREAD

**Issue by UponAnonymous** [wtfnotavailable/Discord-MusicBot#86]
## Is your feature request related to a problem? Please describe.

One of the challenges I have faced when using the bot to play music is the censorship of explicit words in songs sourced from YouTube. Many Spotify links I have sent always have played a clean version of it from YouTube. This censorship can significantly impact the quality and authenticity of the listening experience, especially when a user requests a certain song and it plays something completely different.

## Describe the ideal solution

I would like to suggest a feature that allows the bot to play songs directly from Spotify. This functionality would ensure the preservation of unaltered content, allowing users to experience the music they requested exactly as intended, free from any censorship or modification of explicit lyrics.

## Additional context

The ability to play songs directly from Spotify would be a valuable addition to the bot, addressing the issue of censorship while offering a more enjoyable music listening experience. This feature would align with the desire for unaltered music playback and would be a significant improvement for users who value the song how it was suppose to be heard (unless they requested for the clean version)

**Comment by LewdHuTao** [comment]
Im sure it is not possible to play songs directly from spotify. Lavalink doesn't support playback from spotify it can only convert spotify link to youtube link. Also spotify have strict DRM

**Comment by LewdHuTao** [comment]
If you use your own lavalink you can use LavaSrc plugins in your lavalink. It can search more accurate search results when you play song using spotify links.

**Comment by BioCla** [comment]
This isn't part of the current plan for v5.x, It might be considered as a possible alternative in future versions. If you want to see the feature in the bot you can contribute to the project and it will be greatly appreciated!
